//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BOMBERMANEntities : DbContext
    {
        public BOMBERMANEntities()
            : base("name=BOMBERMANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cell_types> Cell_types { get; set; }
        public DbSet<Games> Games { get; set; }
        public DbSet<Games_details> Games_details { get; set; }
        public DbSet<Games_requests> Games_requests { get; set; }
        public DbSet<Locations> Locations { get; set; }
        public DbSet<Maps> Maps { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<Users_play> Users_play { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
