//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cell_types
    {
        public Cell_types()
        {
            this.Cell_types1 = new HashSet<Cell_types>();
            this.Cell_types11 = new HashSet<Cell_types>();
            this.Games_details = new HashSet<Games_details>();
        }
    
        public int id { get; set; }
        public Nullable<int> exploded_type_to { get; set; }
        public Nullable<int> walked_type_to { get; set; }
        public string name { get; set; }
        public string representation { get; set; }
        public bool explodable { get; set; }
        public bool walkable { get; set; }
        public int powerups_morebomb { get; set; }
        public int powerups_morelevel { get; set; }
        public int powerups_morelife { get; set; }
        public int score { get; set; }
    
        public virtual ICollection<Cell_types> Cell_types1 { get; set; }
        public virtual Cell_types Cell_types2 { get; set; }
        public virtual ICollection<Cell_types> Cell_types11 { get; set; }
        public virtual Cell_types Cell_types3 { get; set; }
        public virtual ICollection<Games_details> Games_details { get; set; }
    }
}
