//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games_requests
    {
        public int id { get; set; }
        public int from_id_user { get; set; }
        public int to_id_user { get; set; }
        public int id_game { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
