//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games_details
    {
        public Games_details()
        {
            this.Locations = new HashSet<Locations>();
        }
    
        public int id { get; set; }
        public byte location_row { get; set; }
        public byte location_column { get; set; }
        public int cell_type_id { get; set; }
        public int game_id { get; set; }
    
        public virtual Cell_types Cell_types { get; set; }
        public virtual Games Games { get; set; }
        public virtual ICollection<Locations> Locations { get; set; }
    }
}
