//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public Games()
        {
            this.Games_details = new HashSet<Games_details>();
            this.Games_requests = new HashSet<Games_requests>();
            this.Users_play = new HashSet<Users_play>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_map { get; set; }
        public int remaining_time { get; set; }
        public bool is_public { get; set; }
        public int owner { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<Games_details> Games_details { get; set; }
        public virtual Maps Maps { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Games_requests> Games_requests { get; set; }
        public virtual ICollection<Users_play> Users_play { get; set; }
    }
}
