//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locations
    {
        public int id { get; set; }
        public int id_gamedet { get; set; }
        public int id_user { get; set; }
        public bool isabomb { get; set; }
        public int bomb_timeout { get; set; }
        public int bomb_level { get; set; }
        public bool isauser { get; set; }
    
        public virtual Games_details Games_details { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
