//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maps
    {
        public Maps()
        {
            this.Games = new HashSet<Games>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public int maplevel { get; set; }
        public string configuration { get; set; }
    
        public virtual ICollection<Games> Games { get; set; }
    }
}
