//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bomberman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Games = new HashSet<Games>();
            this.Games_requests = new HashSet<Games_requests>();
            this.Games_requests1 = new HashSet<Games_requests>();
            this.Locations = new HashSet<Locations>();
            this.Users_play = new HashSet<Users_play>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Games> Games { get; set; }
        public virtual ICollection<Games_requests> Games_requests { get; set; }
        public virtual ICollection<Games_requests> Games_requests1 { get; set; }
        public virtual ICollection<Locations> Locations { get; set; }
        public virtual ICollection<Users_play> Users_play { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
